topics:
  - name: "Machine Learning"
    keywords:
      - "supervised learning"
      - "unsupervised learning"
      - "reinforcement learning"
      - "neural networks"
      - "decision trees"
      - "SVM"
      - "ensemble methods"
      - "clustering"
      - "deep learning"
  - name: "Data Analysis"
    keywords:
      - "statistical analysis"
      - "data visualization"
      - "dimensionality reduction"
      - "feature engineering"
      - "data preprocessing"
      - "time series analysis"
      - "regression analysis"
  - name: "Optimization Techniques"
    keywords:
      - "gradient descent"
      - "convex optimization"
      - "evolutionary algorithms"
      - "genetic algorithms"
      - "bayesian optimization"
      - "linear programming"
  - name: "Natural Language Processing"
    keywords:
      - "text mining"
      - "language modeling"
      - "sentiment analysis"
      - "topic modeling"
      - "transformers"
      - "word embeddings"
      - "sequence-to-sequence models"
  - name: "Computer Vision"
    keywords:
      - "image classification"
      - "object detection"
      - "image segmentation"
      - "convolutional neural networks"
      - "transfer learning"
      - "generative adversarial networks"
  - name: "Theoretical Foundations"
    keywords:
      - "probability theory"
      - "information theory"
      - "statistical learning theory"
      - "complexity theory"
      - "Bayesian inference"
  - name: "Applied AI"
    keywords:
      - "recommender systems"
      - "anomaly detection"
      - "forecasting models"
      - "robotics"
      - "autonomous systems"
      - "AI ethics"
