topics:
  - name: "Machine Learning"
    keywords:
      - "supervised learning"
      - "unsupervised learning"
      - "reinforcement learning"
      - "neural networks"
      - "decision trees"
      - "SVM"
      - "ensemble methods"
      - "clustering"
      - "deep learning"
      - "gradient boosting"
      - "transfer learning"
      - "active learning"
      - "autoML"
      - "model selection"
      - "hyperparameter tuning"
      - "model interpretability"
      - "loss functions"
      - "learning rate"
      - "overfitting"
      - "underfitting"
      - "early stopping"
  - name: "Data Analysis"
    keywords:
      - "statistical analysis"
      - "data visualization"
      - "dimensionality reduction"
      - "feature engineering"
      - "data preprocessing"
      - "time series analysis"
      - "regression analysis"
      - "EDA"
      - "outlier detection"
      - "missing data imputation"
      - "correlation analysis"
      - "descriptive statistics"
      - "hypothesis testing"
      - "anova"
      - "t-test"
      - "z-test"
      - "normality tests"
      - "data transformation"
      - "scaling and normalization"
      - "sampling techniques"
      - "data aggregation"
